// Generated by dia2code
#ifndef STATE__APPARTITIONAREA__H
#define STATE__APPARTITIONAREA__H


namespace state {
  class GameObject;
}

#include "GameObject.h"

namespace state {

  /// class AppartitionArea - 
  class AppartitionArea : public state::GameObject {
    // Setters and Getters
  };

};

#endif
