// Generated by dia2code
#ifndef STATE__CHARACTERSTATE__H
#define STATE__CHARACTERSTATE__H


namespace state {

  enum CharacterState {
    IDLE = 0,
    ATTACK = 1,
    MOVING= 2,
    EVOLVING = 3,
    KILLED = 4,
    INACTIVE = 5
  };

};

#endif
