// Generated by dia2code
#ifndef STATE__CHARACTER__H
#define STATE__CHARACTER__H


namespace state {
  class GameObject;
  class Weapon;
}

#include "GameObject.h"
#include "CharacterState.h"
#include "Weapon.h"

namespace state {

  /// class Character - 
  class Character : public state::GameObject {
    // Associations
    // Attributes
  public:
     id: int = 0;
     lp: int = 0;
     name: string;
    int pm;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
