// Generated by dia2code
#ifndef STATE__DIRECTIONTYPE__H
#define STATE__DIRECTIONTYPE__H


namespace state {

  enum DirectionType {
    FULL = 0,
    DIAGONAL = 1,
    CROSS = 2,
    OCTOPUS = 3
  };

};

#endif
