// Generated by dia2code
#ifndef STATE__GAMEOBJECT__H
#define STATE__GAMEOBJECT__H


namespace state {

  /// class GameObject - 
  class GameObject {
    // Attributes
  public:
    int posX     = 0;
    int posY     = 0;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
