// Generated by dia2code
#ifndef STATE__GAME__H
#define STATE__GAME__H


namespace state {
  class Map;
}

#include "Map.h"

namespace state {

  /// class Game - 
  class Game {
    // Attributes
  public:
     activePlayer: *Player;
    // Operations
  public:
    loadMap (Map map);
    initPlayers ();
    // Setters and Getters
  };

};

#endif
