// Generated by dia2code
#ifndef STATE__GAMESTATE__H
#define STATE__GAMESTATE__H


namespace state {
  class Map;
}

#include "Map.h"

namespace state {

  /// class GameState - 
  class GameState {
    // Attributes
  public:
    *Player activePlayer;
    int turn;
    // Operations
  public:
    loadMap (Map map);
    initPlayers ();
     ();
    // Setters and Getters
  };

};

#endif
