// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <string>

namespace state {
  class Character;
  class Tower;
  class GameObject;
}

#include "Character.h"
#include "Tower.h"
#include "GameObject.h"
#include "TileType.h"

namespace state {

  /// class Map - 
  class Map {
    // Associations
    state::TileType tileElements;
    // Attributes
  public:
    int sizeX;
    int sizeY;
    vector<Character> spawnUnits1;
    vector<Character> spawnUnits2;
    vector<Tower> towers1;
    vector<Tower> towers2;
    vector<GameObject> apparitionAreas1;
    vector<GameObject> apparitionAreas2;
    // Operations
  public:
    Map (std::string mapFile);
    // Setters and Getters
    TileType getTileElements() const;
    void setTileElements(TileType tileElements);
  };

};

#endif
