// Generated by dia2code
#ifndef STATE__PLAYER__H
#define STATE__PLAYER__H


namespace state {
  class Tower;
  class Character;
}

#include "Tower.h"
#include "Character.h"

namespace state {

  /// class Player - 
  class Player {
    // Associations
    // Attributes
  public:
     units: vector<Character>;
     towers: vector<Tower>;
     apparitionAreas: vector<ApparitionArea>;
    // Setters and Getters
  };

};

#endif
