// Generated by dia2code
#ifndef STATE__TILETYPE__H
#define STATE__TILETYPE__H


namespace state {

  enum TileType {
    GRASS = 0,
    TREE = 1,
    MOUNTAIN = 2,
    ROAD = 3,
    SEA = 4
  };

};

#endif
