// Generated by dia2code
#ifndef STATE__TOWER__H
#define STATE__TOWER__H


namespace state {

  /// class Tower - 
  class Tower {
    // Attributes
  public:
     id: int = 0;
     lp: int = 0;
     name: string;
    // Operations
  public:
    void setX (int x);
    // Setters and Getters
  };

};

#endif
