// Generated by dia2code
#ifndef STATE__WEAPON__H
#define STATE__WEAPON__H


#include "DirectionType.h"

namespace state {

  /// class Weapon - 
  class Weapon {
    // Associations
    // Attributes
  public:
    int damage;
    int rangeMin;
    int rangeMax;
    int damageAreaMin;
    int damageAreaMax;
    // Setters and Getters
  };

};

#endif
